### ISSUE TITLE
Lair Actions formatting broken

### ISSUE THREAD

**Issue by daft-develop** [daft-develop/Tetra-cube.github.io#1]
@daft-develop Lair actions seem to be unable to use the same formatting as the rest of the statblock script. In particular, they seem unable to process spaces, italics, die expressions, etc.

(I modified it to say "Regional Effects" instead of "Region Effects" since WotC refers to them as "regional", but I don't know how to fix the formatting.)

![Screenshot (344)](https://user-images.githubusercontent.com/38794241/91242000-40c16600-e714-11ea-99f4-403b17fbc3b7.png)

_Originally posted by @RecursiveStar in https://github.com/Tetra-cube/Tetra-cube.github.io/pull/8#issuecomment-680379233_

**Comment by daft-develop** [comment]
@RecursiveStar, I created an issue tracker on my fork to avoid cluttering the PR with a bunch of comments.

I should be able to look at this sometime this week. Do you want to export the JSON for your example and share it on this issue? I must have not tested formatting on lair actions and regional effects and missed it. It's likely a quick fix on the CSS.

**Comment by daft-develop** [comment]
Hey @RecursiveStar, performed testing with the code and couldn't recreate the problem, appears to work find in both Firefox and Chrome on Windows. See attached aboleth if you want to test or let me know if you're testing under different conditions.

[aboleth.monster.txt](https://github.com/daft-develop/Tetra-cube.github.io/files/5127681/aboleth.monster.txt)

![aboleth output](https://user-images.githubusercontent.com/59496570/91257393-f5648300-e726-11ea-85a7-6156735bced6.png)

**Comment by RecursiveStar** [comment]
@daft-develop My bad! I didn't see the "Add Lair Action/Regional Effect" buttons at the bottom! That explains the problem. :)

It seems that for legendary actions, lair actions, and regional effects, the description doesn't allow for markdown or the special formatting like [1D6] or [STR ATK] or [WIS SAVE] - only the added actions support it.

I appreciate you changing it to Regional and adding the end note!

Two things to note:
"it's lair" for the lair actions description should be "its lair" to be grammatically correct. Also, I think "can take" an action is better wording than "takes an action", since the creature can choose to forgo using its lair actions. See the attached image.

You might want to add an optional end note for the lair actions as well. The Monster Manual description of the beholder has one:
![94f53c7e76c65ef567a27993fe923343](https://user-images.githubusercontent.com/38794241/91348438-c0514280-e7b1-11ea-875e-739ab4820f8a.png)

**Comment by daft-develop** [comment]
Glad to hear it was an easy fix!

I've taken your other feedback notes (much appreciated, thanks for reviewing!) and spun them off into other issues/todo. The grammar and added end note on Lair should be easy, the special formatting in the description _might_ be easy, but it might take a little more effort. You can set up a watch on all the issues or probably the project as a whole and it should ping you as I fix things.
